import { z } from 'zod';
export declare const Format: z.ZodEnum<["1:1", "1.91:1", "4:5", "16:9", "9:16"]>;
export type Format = z.infer<typeof Format>;
export declare const AdDocumentType: z.ZodEnum<["single_image", "carousel", "video"]>;
export type AdDocumentType = z.infer<typeof AdDocumentType>;
export declare const AdDocumentStatus: z.ZodEnum<["draft", "in_review", "approved", "archived"]>;
export type AdDocumentStatus = z.infer<typeof AdDocumentStatus>;
export declare const LayerType: z.ZodEnum<["image", "text", "logo", "shape", "cta", "frame", "legal", "group", "smart"]>;
export type LayerType = z.infer<typeof LayerType>;
export declare const JobStatus: z.ZodEnum<["queued", "dispatched", "running", "succeeded", "failed", "dead", "cancelled", "cached"]>;
export type JobStatus = z.infer<typeof JobStatus>;
export declare const RenderKind: z.ZodEnum<["png", "jpg", "pdf", "svg"]>;
export type RenderKind = z.infer<typeof RenderKind>;
export declare const AgentRunStatus: z.ZodEnum<["queued", "running", "succeeded", "failed", "budget_exceeded"]>;
export type AgentRunStatus = z.infer<typeof AgentRunStatus>;
export declare const EngagementBackend: z.ZodEnum<["saliency", "tribe_research"]>;
export type EngagementBackend = z.infer<typeof EngagementBackend>;
export declare const WorkspaceRole: z.ZodEnum<["owner", "admin", "editor", "viewer"]>;
export type WorkspaceRole = z.infer<typeof WorkspaceRole>;
export declare const Locale: z.ZodEnum<["de", "en"]>;
export type Locale = z.infer<typeof Locale>;
